CREATE TABLE IF NOT EXISTS certificate_expirations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    domain VARCHAR NOT NULL UNIQUE,
    expiration_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS web_hooks (
    id BIGINT PRIMARY KEY GENERATED  BY DEFAULT AS IDENTITY,
    callback_url VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS expiration_check_records (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    domain VARCHAR NOT NULL,
    expiration_date timestamptz NOT NULL,
    days_left INTEGER NOT NULL,
    exceeds_threshold BOOL NOT NULL,
    is_expired BOOL NOT NULL,
    threshold INTEGER NOT NULL ,
    created_at timestamptz NOT NULL
)