services:
  postgres-db:
    container_name: dom-monitor-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dom_monitor
    ports:
      - "5434:5432"
    volumes:
      - dom-monitor-db-data:/var/lib/postgresql/data
    networks:
      - dom-monitor-network
    restart: "unless-stopped"

volumes:
  dom-monitor-db-data:
    name: dom-monitor-db-data
    driver: local

networks:
  dom-monitor-network:
    name: dom-monitor-network